### ISSUE TITLE
🐛 Error building docker image

### ISSUE THREAD

**Issue by tobiasgiese** [loafoe/hubot-matteruser#144]
While building the docker image, I get the following error

```
Step 14/18 : RUN echo "No" | yo hubot --adapter matteruser --owner="${hubot_owner}" --name="${hubot_name}" --description="${hubot_desciption}" --defaults && sed -i '/heroku/d' external-scripts.json
 ---> Running in 57e4f74689c8
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70
    filePatterns: lookups.flatMap(prefix => [`${prefix}/*/index.ts`, `${prefix}/*/index.js`, `${prefix}/*/index.cjs`, `${prefix}/*/index.mjs`]),
                          ^

TypeError: lookups.flatMap is not a function
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:70:27)
    at init (/usr/local/lib/node_modules/yo/lib/cli.js:130:7)
    at Immediate.pre (/usr/local/lib/node_modules/yo/lib/cli.js:89:3)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
The command '/bin/sh -c echo "No" | yo hubot --adapter matteruser --owner="${hubot_owner}" --name="${hubot_name}" --description="${hubot_desciption}" --defaults && sed -i '/heroku/d' external-scripts.json' returned a non-zero code: 1
```

Potential workaround is to install an older `yo` version

```
RUN npm install -g yo@3.1.1
```

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

**Comment by loafoe** [comment]
updated base to `node:14` which solved it

**Comment by tobiasgiese** [comment]
Thanks @loafoe 👍🏻 :)

**Comment by loafoe** [comment]
@tobiasgiese thx for the PR to `alpine` to reduce the massive bloat :)
