### ISSUE TITLE
ERROR TypeError: Cannot set property 'dm_channel_id' of undefined

### ISSUE THREAD

**Issue by gajus** [loafoe/hubot-matteruser#23]
```diff
[gajus@mattermost myhubot]$ ./bin/hubot --adapter matteruser
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Logging in...
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Websocket URL: wss://messaging.anuary.com:443/api/v3/users/websocket
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Logged in as user "january" but not connected yet.
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Connecting...
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] ERROR Failed to load profiles from server.
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Error: [object Object]
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Connected to Mattermost.
[Wed Nov 23 2016 14:29:10 GMT+0000 (UTC)] INFO Starting pinger...
[Wed Nov 23 2016 14:29:11 GMT+0000 (UTC)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Wed Nov 23 2016 14:29:11 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Wed Nov 23 2016 14:29:11 GMT+0000 (UTC)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Wed Nov 23 2016 14:29:11 GMT+0000 (UTC)] INFO Brain loaded
+[Wed Nov 23 2016 14:29:29 GMT+0000 (UTC)] ERROR TypeError: Cannot set property 'dm_channel_id' of undefined
+  at Matteruser.message (/home/gajus/myhubot/node_modules/hubot-matteruser/src/matteruser.coffee:133:11, <js>:206:31)
+  at Client.<anonymous> (/home/gajus/myhubot/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:3:61)
+  at emitOne (events.js:96:13)
+  at Client.emit (events.js:188:7)
+  at Client.onMessage (/home/gajus/myhubot/node_modules/mattermost-client/src/client.coffee:211:17, <js>:278:23)
+  at WebSocket.<anonymous> (/home/gajus/myhubot/node_modules/mattermost-client/src/client.coffee:158:13, <js>:217:22)
+  at emitTwo (events.js:106:13)
+  at WebSocket.emit (events.js:191:7)
+  at Receiver.ontext (/home/gajus/myhubot/node_modules/ws/lib/WebSocket.js:841:10)
+  at /home/gajus/myhubot/node_modules/ws/lib/Receiver.js:536:18
+  at Receiver.applyExtensions (/home/gajus/myhubot/node_modules/ws/lib/Receiver.js:371:5)
+  at /home/gajus/myhubot/node_modules/ws/lib/Receiver.js:508:14
+  at Receiver.flush (/home/gajus/myhubot/node_modules/ws/lib/Receiver.js:347:3)
+  at Receiver.finish (/home/gajus/myhubot/node_modules/ws/lib/Receiver.js:541:12)
+  at Receiver.expectHandler (/home/gajus/myhubot/node_modules/ws/lib/Receiver.js:499:31)
+  at Receiver.add (/home/gajus/myhubot/node_modules/ws/lib/Receiver.js:103:24)
+  at TLSSocket.realHandler (/home/gajus/myhubot/node_modules/ws/lib/WebSocket.js:825:20)
+  at emitOne (events.js:96:13)
+  at TLSSocket.emit (events.js:188:7)
+  at readableAddChunk (_stream_readable.js:176:18)
+  at TLSSocket.Readable.push (_stream_readable.js:134:10)
+  at TLSWrap.onread (net.js:551:20)
```

I have got this error after sending a private message to the bot.

**Comment by loafoe** [comment]
@gajus the below error message probably explains this:

**ERROR Failed to load profiles from server.**

Make sure you are using Mattermost `3.5.x`. Unfortunately the adapter is only compatible with the latest version as the server API is really volatile. 

Also please upgrade to version `3.5.1` of *hubot-matteruser* which I just released. It contains some fixed which might help.

**Comment by nickolasclarke** [comment]
I'm also seeing this. I am on `"hubot-matteruser": "^3.5.1",` perhaps it is related to:
 ``` 
[Wed Dec 14 2016 19:49:24 GMT+0800 (DST)] ERROR Failed to load profiles from server.
[Wed Dec 14 2016 19:49:24 GMT+0800 (DST)] INFO Error: [object Object]
``` 

full dump:
``` 
nclarke@NCLARKE:~/repos/hubot$ ./bin/hubot -a matteruser
[Wed Dec 14 2016 19:48:43 GMT+0800 (DST)] INFO Logging in...
[Wed Dec 14 2016 19:48:43 GMT+0800 (DST)] DEBUG POST /users/login

[Wed Dec 14 2016 19:48:54 GMT+0800 (DST)] INFO Websocket URL: wss://myserver.org:443/api/v3/users/websocket
[Wed Dec 14 2016 19:48:54 GMT+0800 (DST)] INFO Logged in as user "hubot" but not connected yet.
[Wed Dec 14 2016 19:48:54 GMT+0800 (DST)] DEBUG GET /users/initial_load
[Wed Dec 14 2016 19:49:05 GMT+0800 (DST)] DEBUG Found 1 teams.
[Wed Dec 14 2016 19:49:16 GMT+0800 (DST)] DEBUG Testing myteam == myteam
[Wed Dec 14 2016 19:49:16 GMT+0800 (DST)] DEBUG Found team! tauuaunahbg9ppichcqeh77gko
[Wed Dec 14 2016 19:49:16 GMT+0800 (DST)] DEBUG GET /teams/tauuaunahbg9ppichcqeh77gko/users/0/1000
[Wed Dec 14 2016 19:49:16 GMT+0800 (DST)] DEBUG GET /teams/tauuaunahbg9ppichcqeh77gko/channels/
[Wed Dec 14 2016 19:49:16 GMT+0800 (DST)] INFO Connecting...
[Wed Dec 14 2016 19:49:22 GMT+0800 (DST)] INFO Connected to Mattermost.
[Wed Dec 14 2016 19:49:22 GMT+0800 (DST)] INFO Starting pinger...
[Wed Dec 14 2016 19:49:23 GMT+0800 (DST)] INFO Mattermost server: 3.4.0.3.4.0.d8ef17d8078e1051eb91f9b08217891d

[Wed Dec 14 2016 19:49:24 GMT+0800 (DST)] ERROR Failed to load profiles from server.
[Wed Dec 14 2016 19:49:24 GMT+0800 (DST)] INFO Error: [object Object]
[Wed Dec 14 2016 19:49:52 GMT+0800 (DST)] INFO ping
[Wed Dec 14 2016 19:49:52 GMT+0800 (DST)] INFO ACK ping

[Wed Dec 14 2016 19:50:06 GMT+0800 (DST)] ERROR TypeError: Cannot set property 'dm_channel_id' of undefined
  at Matteruser.message (/home/nclarke/repos/hubot/node_modules/hubot-matteruser/src/matteruser.coffee:138:11, <js>:213:31)
  at Client.<anonymous> (/home/nclarke/repos/hubot/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:3:61)
  at emitOne (events.js:96:13)
  at Client.emit (events.js:188:7)
  at Client.onMessage (/home/nclarke/repos/hubot/node_modules/mattermost-client/src/client.coffee:210:17, <js>:277:23)
  at WebSocket.<anonymous> (/home/nclarke/repos/hubot/node_modules/mattermost-client/src/client.coffee:157:13, <js>:216:22)
  at emitTwo (events.js:106:13)
  at WebSocket.emit (events.js:191:7)
  at Receiver.ontext (/home/nclarke/repos/hubot/node_modules/ws/lib/WebSocket.js:841:10)
  at /home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:371:5)
  at /home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.finish (/home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/home/nclarke/repos/hubot/node_modules/ws/lib/Receiver.js:103:24)
  at TLSSocket.realHandler (/home/nclarke/repos/hubot/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:96:13)
  at TLSSocket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at TLSSocket.Readable.push (_stream_readable.js:134:10)
  at TLSWrap.onread (net.js:548:20)

```

**Comment by nickolasclarke** [comment]
turns out we are mattermost server 3.4. I thought we were on 3.5. I'm putting in a request to have the server upgraded to the latest version, and if this is still an issue, I'll let you know.

**Comment by loafoe** [comment]
@nickolasclarke ok, keep us posted. thx for the feedback!

**Comment by elsifaka** [comment]
I have mattermost 3.5.1, hubot 2.19.0, mattermost-client 3.5.1 and hubot-matteruser 3.5.1 and saw the same issue.
But only when an user from a different team send a DM to the bot. everything works fine in group channels.
The bot has been invited to all teams, but robot brain only has data for the users of the group set with MATTERMOST_GROUP.

**Comment by loafoe** [comment]
@elsifaka ah, interesting! Indeed the bot only loads one single group. I think we could add support for multiple groups in a future release.

@nickolasclarke do you also have multiple groups on your Mattermost server?

**Comment by nickolasclarke** [comment]
@loafoe nope. Also, forgot to update this. Upgrading indeed fixed the issue.
