### ISSUE TITLE
May be incompatible with hubot@3?

### ISSUE THREAD

**Issue by ccoenen** [loafoe/hubot-matteruser#64]
I was just trying to upgrade all my hubot things, and I went with `hubot@3.0.1`. This yielded errors here:

https://github.com/loafoe/hubot-matteruser/blob/fdf4cdb883eb6addccc71bb9ce24a55d942baa49/src/matteruser.coffee#L201

I commented this line out to see if it the ignored users. The error just shifted to just a few lines later:

https://github.com/loafoe/hubot-matteruser/blob/fdf4cdb883eb6addccc71bb9ce24a55d942baa49/src/matteruser.coffee#L207

```
INFO Someone is typing...
DEBUG Message {
  event: 'posted',
  data:
   { channel_display_name: '',
     channel_name: 'my8---redacted---br6c',
     channel_type: 'D',
     mentions: '["no4--redacted--br6c"]',
     post: '{"id":"ke3----tc","create_at":1522146010510,"update_at":1522146010510,"edit_at":0,"delete_at":0,"is_pinned":false,"user_id":"my8---t1h9e","channel_id":"rn----wa","root_id":"","parent_id":"","original_id":"","message":"help","type":"","props":{},"hashtags":"","pending_post_id":"my8------h9e:1522146010862"}',
     sender_name: 'mynickname',
     team_id: '' },
  broadcast:
   { omit_users: null,
     user_id: '',
     channel_id: 'rn83---redacted--cwa',
     team_id: '' },
  seq: 4 }
ERROR TypeError: Cannot read property 'getUserByID' of undefined
  at Matteruser.message (--redacted--\node_modules\hubot-matteruser\src\matteruser.coffee:207:18, <js>:289:28)
  at Client.<anonymous> (--redacted--\node_modules\hubot-matteruser\src\matteruser.coffee:1:1, <js>:5:61)
  at Client.emit (events.js:160:13)
  at Client.onMessage (--redacted--\node_modules\mattermost-client\src\client.coffee:279:17, <js>:381:23)
  at WebSocket.<anonymous> (--redacted--\node_modules\mattermost-client\src\client.coffee:224:13, <js>:318:22)
  at WebSocket.emit (events.js:160:13)
  at Receiver.ontext (--redacted--\node_modules\ws\lib\WebSocket.js:841:10)
  at --redacted--\node_modules\ws\lib\Receiver.js:536:18
  at Receiver.applyExtensions (--redacted--\node_modules\ws\lib\Receiver.js:371:5)
  at --redacted--\node_modules\ws\lib\Receiver.js:508:14
  at Receiver.flush (--redacted--\node_modules\ws\lib\Receiver.js:347:3)
  at Receiver.finish (--redacted--\node_modules\ws\lib\Receiver.js:541:12)
  at Receiver.expectHandler (--redacted--\node_modules\ws\lib\Receiver.js:499:31)
  at Receiver.add (--redacted--\node_modules\ws\lib\Receiver.js:103:24)
  at TLSSocket.realHandler (--redacted--\node_modules\ws\lib\WebSocket.js:825:20)
  at TLSSocket.emit (events.js:160:13)
  at addChunk (_stream_readable.js:269:12)
  at readableAddChunk (_stream_readable.js:256:11)
  at TLSSocket.Readable.push (_stream_readable.js:213:10)
  at TLSWrap.onread (net.js:599:20)

INFO ping
```

**Comment by ketchalegend** [comment]
Could you solve the problem? I am having the same issue here.

**Comment by ccoenen** [comment]
my solution at the time was to downgrade hubot, which I've been using ever since. Not ideal.

**Comment by loafoe** [comment]
@ketchalegend @ccoenen the next version (5.x) should be compatible with Hubot3. If you are able to test the current `master` branch that would be great!

**Comment by ccoenen** [comment]
I'm very sorry, My bot is currently running well enough and I am somewhat swamped. I will not be able to test this in the next 3-4 weeks. This is not for a lack of interest, though. I will update to 3.x at some point.

**Comment by loafoe** [comment]
@ketchalegend @ccoenen there is a new `v5.0.0` which should be fully compatible with Hubot3, please try it and report any issues.
