### ISSUE TITLE
docker troubles

### ISSUE THREAD

**Issue by the-herbivore** [loafoe/hubot-matteruser#68]
Hi,

I am receiving the following error when attempting to build using `docker-compose` -

```
Step 14/18 : RUN echo "No" | yo hubot --adapter matteruser --owner="${hubot_owner}" --name="${hubot_name}" --description="${hubot_desciption}" --defaults && sed -i '/heroku/d' external-scripts.json
 ---> Running in 8bc2a25c8fc7
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:165
    let lookup = path.join(...parts.slice(0, i + 1), 'node_modules');
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:14:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
ERROR: Service 'hubot-matteruser' failed to build: The command '/bin/sh -c echo "No" | yo hubot --adapter matteruser --owner="${hubot_owner}" --name="${hubot_name}" --description="${hubot_desciption}" --defaults && sed -i '/heroku/d' external-scripts.json' returned a non-zero code: 1
```

with an appropriately configured `docker-compose.yml`.

This is occurring on multiple OSes/docker versions, too

Any ideas?

**Comment by xurizaemon** [comment]
"Unexpected token ..." - suggest to me the JavaScript without es6 features? I don't know how likely that is, but can you add detail about the version of js running in that docker image?

**Comment by matfiz** [comment]
This is the fault of old docker node image - check my PR :)

**Comment by loafoe** [comment]
Thanks @matfiz , merged
