### ISSUE TITLE
indexOf on null or undefined

### ISSUE THREAD

**Issue by Novitsh** [loafoe/hubot-matteruser#77]
I have the feeling the bot is unable to read usernames or user ids?

[Fri Oct 05 2018 10:02:20 GMT+0200 (CEST)] INFO Connected to Mattermost.
[Fri Oct 05 2018 10:02:20 GMT+0200 (CEST)] INFO Sending challenge...
[Fri Oct 05 2018 10:02:20 GMT+0200 (CEST)] INFO Starting pinger...
[Fri Oct 05 2018 10:02:20 GMT+0200 (CEST)] INFO Mattermost server: 5.1.0.5.1.1.0dbba7b51909dd7ab49afd949f5619cd.false
[Fri Oct 05 2018 10:02:20 GMT+0200 (CEST)] INFO Found 0 profiles.
[Fri Oct 05 2018 10:02:22 GMT+0200 (CEST)] INFO Someone is typing...
[Fri Oct 05 2018 10:02:23 GMT+0200 (CEST)] ERROR TypeError: Array.prototype.indexOf called on null or undefined
  at indexOf (<anonymous>:null:null)
  at Matteruser.message (/shared/httpd/jarvis/node_modules/hubot-matteruser/src/matteruser.coffee:201:36, <js>:288:51)
  at Client.<anonymous> (/shared/httpd/jarvis/node_modules/hubot-matteruser/src/matteruser.coffee:1:1, <js>:5:61)
  at emitOne (events.js:116:13)
  at Client.emit (events.js:211:7)
  at Client.onMessage (/shared/httpd/jarvis/node_modules/mattermost-client/src/client.coffee:279:17, <js>:381:23)
  at WebSocket.<anonymous> (/shared/httpd/jarvis/node_modules/mattermost-client/src/client.coffee:224:13, <js>:318:22)
  at emitTwo (events.js:126:13)
  at WebSocket.emit (events.js:214:7)
  at Receiver.ontext (/shared/httpd/jarvis/node_modules/ws/lib/WebSocket.js:841:10)
  at /shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:536:18
  at Receiver.applyExtensions (/shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:371:5)
  at /shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:508:14
  at Receiver.flush (/shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:347:3)
  at Receiver.finish (/shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:541:12)
  at Receiver.expectHandler (/shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:499:31)
  at Receiver.add (/shared/httpd/jarvis/node_modules/ws/lib/Receiver.js:103:24)
  at TLSSocket.realHandler (/shared/httpd/jarvis/node_modules/ws/lib/WebSocket.js:825:20)
  at emitOne (events.js:116:13)
  at TLSSocket.emit (events.js:211:7)
  at addChunk (_stream_readable.js:263:12)
  at readableAddChunk (_stream_readable.js:250:11)
  at TLSSocket.Readable.push (_stream_readable.js:208:10)
  at TLSWrap.onread (net.js:601:20)

**Comment by Novitsh** [comment]
Duplicate of #73
